<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>SharpHoundRPC</PackageId>
        <PackageDescription>SAM/LSA Wrapper for C# BloodHound tasks</PackageDescription>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <AssemblyName>SharpHoundRPC</AssemblyName>
        <RootNamespace>SharpHoundRPC</RootNamespace>
    </PropertyGroup>
    <PropertyGroup>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
        <DebugType>full</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="System.ValueTuple" Version="4.5.0"/>
    </ItemGroup>
    <ItemGroup>
        <Reference Include="System.Management" />
    </ItemGroup>
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>
