name: Build and Test

on:
  pull_request:
    branches:
      - v4

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # ratchet:actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
  
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -p:BuildDocFx=false

      - name: Test
        run: dotnet test --no-build
